<a href="https://colab.research.google.com/github/grammukuttyma103-stack/Data-Analytics-using-Python-Project/blob/main/DAY3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
try:
  num=int(input("Enter Number:"))
  print(num)
except:
  print("Invalid Input")

Enter Number:6
6


In [ ]:
def calculate_average(m1, m2, m3):
    return (m1 + m2 + m3) / 3

try:
    mark1 = float(input("Enter Mark 1: "))
    mark2 = float(input("Enter Mark 2: "))
    mark3 = float(input("Enter Mark 3: "))

    avg = calculate_average(mark1, mark2, mark3)

    print("Average =", avg)

    if avg >= 75:
        print("Grade: A")
    elif avg >= 60:
        print("Grade: B")
    elif avg >= 50:
        print("Grade: C")
    else:
        print("Grade: F")

except ValueError:
    print("Please enter valid numbers")

Enter Mark 1: 98
Enter Mark 2: 76
Enter Mark 3: 90
Average = 88.0
Grade: A


In [ ]:
import numpy as np

marks=np.array([90,76,98,99])

print(marks)

[90 76 98 99]


In [ ]:
import numpy as np

students = np.array([
    [99,95],
    [88,94],
    [76,77],
])
print(students)

[[99 95]
 [88 94]
 [76 77]]


In [ ]:
import numpy as np
arr=np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]
